version: '3.7'

services:

  robocleaner:
    image: marshmallow/robocleaner:latest
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms64m -Xmx512m
      - spring.profiles.active=live
